# Generated by Django 3.2.6 on 2022-03-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_centralizedadminview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('doc_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_id', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
            ],
        ),
    ]
