# Generated by Django 3.2.6 on 2022-04-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_ipdadmission_primary_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdadmission',
            name='bed_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ipdpatientenquiry',
            name='bed_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ipdpatientenquiry',
            name='ipd_no',
            field=models.IntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ipdpatientsearch',
            name='bed_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ipdpatientsearch',
            name='ipd_no',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
