# Generated by Django 3.2.6 on 2022-04-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20220409_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdpatientenquiry',
            name='ipd_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='ipdpatientsearch',
            name='ipd_no',
            field=models.IntegerField(unique=True),
        ),
    ]
