# Generated by Django 4.0.1 on 2022-05-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_centralizedadminview_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centralizedadminview',
            name='store_image',
        ),
        migrations.AddField(
            model_name='centralizedadminview',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
