# Generated by Django 4.0.1 on 2022-05-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_centralizedadminview_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAdminView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_km', models.CharField(blank=True, max_length=100, null=True)),
                ('store_item', models.CharField(blank=True, max_length=100, null=True)),
                ('store_min_order', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CentralizedAdminView',
        ),
    ]
